const API_KEY = process.env.API_KEY
const API_SECRET = process.env.API_SECRET
const BOT_TOKEN = process.env.BOT_TOKEN
const BOT_TOKEN_GUEST = process.env.BOT_TOKEN_GUEST
const BOT_TOKEN_SERVICE = process.env.BOT_TOKEN_SERVICE
const BOT_TOKEN_TRX_WALLET = process.env.BOT_TOKEN_TRX_WALLET
const BOT_TOKEN_TRX_WALLET_CLIENT = process.env.BOT_TOKEN_TRX_WALLET_CLIENT
const LIST_CHAT_ID = [
  '-4194909863',
  '-4117216942'
]
const LIST_COIN = [
  //'BNB',
  'USDT',
]

module.exports = {
  API_KEY,
  API_SECRET,
  BOT_TOKEN,
  LIST_CHAT_ID,
  LIST_COIN,
  BOT_TOKEN_GUEST,
  BOT_TOKEN_SERVICE,
  BOT_TOKEN_TRX_WALLET,
  BOT_TOKEN_TRX_WALLET_CLIENT
}
